# Generated by Django 5.0 on 2024-03-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scratch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="TournamentRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scratch.player"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scratch.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="registered_players",
            field=models.ManyToManyField(
                related_name="tournaments",
                through="scratch.TournamentRegistration",
                to="scratch.player",
            ),
        ),
    ]
