# Generated by Django 5.0 on 2024-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scratch", "0002_tournament_status_tournamentregistration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="registered_players",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not started", "Not started"),
                    ("Started", "Started"),
                    ("Completed", "Completed"),
                ],
                default="Not started",
                max_length=12,
            ),
        ),
    ]
