# Generated by Django 5.0 on 2024-03-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scratch", "0003_remove_tournament_registered_players_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="registered_players",
            field=models.ManyToManyField(
                related_name="tournaments",
                through="scratch.TournamentRegistration",
                to="scratch.player",
            ),
        ),
    ]
